name: Publish
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  publish:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        id: download
        with:
          name: 'packages'
          path: './packages'

      - name: Publish packages
        uses: './.github/actions/dotnet/nuget'
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          packages-directory: '${{steps.download.outputs.download-path}}/${{ inputs.environment }}'